server_port: 1900
log_file: "logs/database_operation/"
database_ip: "192.168.1.1"
database_port: 3306
database_privilege_user: "root"
database_privilege_password: "123456"
user_database_name: "cross-do"
log_config: "logs_config/"