server_port: 1900
log_file: /home/cross/logs/database_operation/
log_config: /home/cross/config/zlog.conf
database_ip: 192.168.1.1
database_port: 3306
database_privilege_user: root
database_privilege_password: 123456
database_pool_size: 10
user_database_name: cross-do
redis_server: 192.168.1.2
redis_port: 6379
redis_password: 123456
redis_pool_size: 10